language: objective-c
osx_image: xcode7.3
sudo: false
env:
  global:
    - FRAMEWORK_NAME=UIImageAutoresize
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=UIImage+Autoresize.xcworkspace
    - IOS_FRAMEWORK_SCHEME="UIImageAutoresize"
    - IOS_SDK=iphonesimulator9.3
    - IOS_EXAMPLE_SCHEME="Example"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4s"
    - DESTINATION="OS=8.3,name=iPhone 5s"
    - DESTINATION="OS=9.2,name=iPhone 6s"
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"
    - DESTINATION="OS=9.1,name=iPad Air 2"
    - DESTINATION="OS=9.3,name=iPad Pro"
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - set -o pipefail
  # Build Framework and Run Tests
  - xctool -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES build test
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  user: kevindelord
  password:
    secure: PJvGtPvY9j8T0sbF9r7kH5sBgXAQZZAUDTPBhQzqqo7JW9toTn1j7sQm6KKUX2xzNorOMd3DDNQ7s4M1EfcmnSRC1qzw1oY0ZYhKSRXVySwFIdhxbTnGYeRUD8NMFsdiOvrn48zhvIrD8qsb60kIYz4/APLdkKSfXsoqZmyZo6Uxb/kalQZHCrEN1HjAXEwjCvRG1HOLa2It9RFeu7fgKCZVEEb7DruAYtHwb00eyTONeZwjOMEO5jaaz71U70pW3hOvGN2NXQuZhhZyUmfhVReeZZ4TUWE9Su76sbBdC5w5H+45pWgYuPfL3sjhPCNsgOlEREXOZwRji0eWeoFaAshQEudj4z7KVHVHo4bxVr9YEt7DR830VKEtAfXK381GT39s2o/ANYseccsd23IEI/kkM7IOygVVb+F74A+HkIHGa1bJLORLJEHAp1G7CX3xWX00BGjBExDtb2DchDT4diIDfNg5b9xAXlNjPueOI1L95po5jP+MF9CvEa8uJOBU8n6QWIjCht6s+3bflb15rnvsNQtyQreF30sRO+SKojJHgEVszfIRktD4XWnDuEa6X9eMIJvE1hycAQre9HIKkUa/mG+K/+jKCWtW2bBSXu3Ur2EZdYpCuJ3sYDbPv/UoogjSshGF2XoMpKdnEn7G31SvsA/SAwnv9uGZbZ8VzY8=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: kevindelord/UIImage-Autoresize
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
