language: objective-c
osx_image: xcode7.3
xcode_project: UIImage+Autoresize.xcodeproj
xcode_scheme: UIImageAutoresize
xcode_sdk: iphonesimulator9.3
xctool_args: -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" GCC_GENERATE_TEST_COVERAGE_FILES=YES
  GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
sudo: false
env:
  global:
  - FRAMEWORK_NAME=UIImageAutoresize
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: fQZME/RZo0ttf6+M+o8WCCdeQf6ZY4wK+VXFqwGws7BSoEqmI12gQmgD1+EYlc276vTNz9zxhB5YyI84HBsJmkN3/zAW1dPVxVi8jHFStjAZvPLzbFcFzdyfL1ejmG4Z66flbiXUQkR3jbD5CNxQloxI47qM/IjuHWXwHz9XXW/lJKQT69sAkmUgZDEmyu9ZbELAyxCqPSNF40SzAflS8NlaTSFuxcgwV3SbJ8P5DgZAOPr5DRvZm6fqayfqK3Djl2bRGQo5qHg1fB0nEArK6JpDI389ujPLjDnMoqDbe/h8YD2CBTl4uWM2VDtlpQNF18MrVX6EJKr37P3IoQX6h2HUbdI+BsO3FHaQIpSe3xdHWQmILApZW74pwQzLZqtH7CGYbQAS003z27QCTELR28nMDwj/Cx+HJ3dL480b84TYdOc/VG/MnMkyFBpfJqlderyQd7RY2CK0WF8LqvReJHq4NRn/S0y5PZbuXrZ4TOLEr22LWA+SR4RIfBi1UHPgoqODHBxJ4qHCaVt7ZjkhjCPAfxJbPWQ1lKLGfD4u7jaWLZ9kxyPUl0hbJROeWvIdveuFRp2tOkyYgAKL03qqMS5MpJ8uR8JHjDL1PkfK3GBYEaohJrPDaJbdQgQsjNAJf58kUX0b4FWrLZ9oxw9ceUJuiatX9qtfxFPjABQtge8=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: kevindelord/UIImage-Autoresize
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)